# This workflow will build and push a node.js application to an Azure Web App when a release is created.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on: [push]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - shell: bash
      run: |
          pwd
    - name: 'npm install, build, and test'
      run: |
        npm install
               
    # deploy web app using Azure credentials
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r test.zip .

    - shell: bash
      env: # Or as an environment variable
        AZURE_WEBAPP_PUBLISHING_USER: ${{ secrets.AZURE_WEBAPP_PUBLISHING_USER }}
        AZURE_WEBAPP_PUBLISHING_PWD: ${{ secrets.AZURE_WEBAPP_PUBLISHING_PWD }}
        AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
        AZURE_DEFAULT_HOST: ${{ secrets.AZURE_DEFAULT_HOST }}
      run: |
        curl --data-binary @test.zip --insecure https://$AZURE_WEBAPP_PUBLISHING_USER:$AZURE_WEBAPP_PUBLISHING_PWD@App1.scm.anwestgk8se.k4apps-test.io/api/zipdeploy -v
